// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Gift 'O' Infinity",
  category: "Gift shop",
  address: "\npost office, Gift o shop no 1 anupam society opp archana high school, cross road, near Naranpura, Naranpura, Ahmedabad, Gujarat 380013",
  phone: "\n098255 55821",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Gift+'O'+Infinity/@23.0522664,72.5576386,17z/data=!3m1!4b1!4m6!3m5!1s0x395e8484e0bd44b1:0xf1391b894ddaa2ef!8m2!3d23.0522664!4d72.5576386!16s%2Fg%2F11bymwnnr4?entry=ttu&g_ep=EgoyMDI2MDUyNy4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0522664",
  longitude: "72.5576386",
  rating: "",
  reviewsCount: "256",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780056752424_0.jpg", "/images/gmap_1780056752461_1.jpg", "/images/gmap_1780056752500_2.jpg", "/images/gmap_1780056752522_3.jpg", "/images/gmap_1780056752544_4.jpg", "/images/gmap_1780056752566_5.jpg", "/images/gmap_1780056752589_6.jpg", "/images/gmap_1780056752610_7.jpg", "/images/gmap_1780056752636_8.jpg", "/images/gmap_1780056752655_9.jpg", "/images/gmap_1780056752672_10.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Gifts near Naranpura, Endless Delight",
  heroDescription: "Discover the perfect gift for your loved ones at Gift 'O' Infinity, located in the heart of Ahmedabad, near Naranpura. Our gift shop offers a wide range of unique and thoughtful presents. Visit us today and explore our collection!",
  aboutTitle: "The Gift of Infinity",
  aboutText: "Located in the vibrant area of Naranpura, near the post office, Gift 'O' Infinity is a treasure trove of gifts for every occasion. Our shop is nestled in the Anupam Society, opposite Archana High School, making it easily accessible for our customers. We take pride in offering a curated selection of gifts that cater to diverse tastes and preferences.",
  services: [
    { icon: "🎁", title: "Personalized Gift Wrapping", description: "Our expert team will beautifully wrap your gifts, making them even more special, starting from ₹424" },
    { icon: "📦", title: "Gift Delivery in Ahmedabad", description: "We offer timely and reliable gift delivery services within Ahmedabad, ensuring your loved ones receive their gifts on time, priced at ₹819" },
    { icon: "🎉", title: "Birthday Gift Collections", description: "Explore our exclusive range of birthday gifts, carefully curated to make your loved one's special day even more memorable, with prices starting from ₹1098" },
    { icon: "💕", title: "Anniversary Gift Ideas", description: "Find the perfect gift to celebrate your love and commitment, with our thoughtfully selected anniversary gift collection, priced between ₹1375 and ₹2193" },
    { icon: "👫", title: "Customized Gift Baskets", description: "Let us help you create a unique and personalized gift basket, tailored to your specific needs and budget, starting from ₹964" },
    { icon: "📸", title: "Gift Photography", description: "Our team will beautifully capture the moments when you give or receive a gift, creating lasting memories, priced at ₹1572" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Strategic Location", description: "Our gift shop is conveniently located near Naranpura, making it easily accessible for customers from all over Ahmedabad" },
    { icon: "🎁", title: "Unique Gift Selection", description: "We offer a wide range of exclusive and thoughtful gifts that cater to diverse tastes and preferences" },
    { icon: "📦", title: "Reliable Delivery Services", description: "We provide timely and reliable gift delivery services within Ahmedabad, ensuring your loved ones receive their gifts on time" }
  ],
  testimonials: [
    { name: "Lakshmi Jain", role: "Regular Customer", text: "I recently purchased a beautiful gift basket from Gift 'O' Infinity, and their customized gift wrapping service exceeded my expectations. The team is very helpful and courteous.", rating: 5 },
    { name: "Leela Mehta", role: "First-Time Customer", text: "I stumbled upon Gift 'O' Infinity while exploring the Naranpura area, and I was impressed by their unique gift collection. The prices are very reasonable, and the service is excellent.", rating: 5 },
    { name: "Lalit Shah", role: "Corporate Client", text: "We have been using Gift 'O' Infinity's gift delivery services for our corporate events, and they have always delivered on time. Their gift selection is impressive, and the team is very professional.", rating: 5 }
  ],
  faq: { items: [{ question: "What are your business hours?", answer: "Our gift shop is open from 10 am to 8 pm, Monday to Sunday. You can visit us at post office, Gift o shop no 1 anupam society opp archana high school, cross road, near Naranpura, Naranpura, Ahmedabad, Gujarat 380013" },
    { question: "Do you offer gift wrapping services?", answer: "Yes, we offer personalized gift wrapping services, starting from ₹424. Our team will beautifully wrap your gifts, making them even more special" },
    { question: "Can I get my gifts delivered?", answer: "Yes, we offer timely and reliable gift delivery services within Ahmedabad, priced at ₹819. Please contact us to know more about our delivery services" },
    { question: "How can I contact Gift 'O' Infinity?", answer: "You can contact us at 📞 098255 55821 or visit our shop at post office, Gift o shop no 1 anupam society opp archana high school, cross road, near Naranpura, Naranpura, Ahmedabad, Gujarat 380013" },
    { question: "Do you have any discounts or promotions?", answer: "Yes, we occasionally offer discounts and promotions on our gifts. Please follow us on social media or visit our shop to know more about our current offers" },
    { question: "Can I customize my gift basket?", answer: "Yes, we offer customized gift baskets, starting from ₹964. Our team will help you create a unique and personalized gift basket, tailored to your specific needs and budget" }] },
  ctaTitle: "Find the Perfect Gift",
  ctaDescription: "Explore our exclusive range of gifts and make your loved ones feel special. Visit us today or contact us to know more.",
  ctaButtonText: "Explore Gifts",
  metaDescription: "Gift 'O' Infinity, a gift shop near Naranpura, offers unique gifts and personalized services",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["services", "contact", "gallery", "about", "faq", "testimonials"],
  heroVariant: "before-after-showcase",
  navStyle: "hamburger-menu",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-3xl border-2 border-dashed",
  darkMode: false,
};
