// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Gift 'O' Infinity",
  category: "Gift shop",
  address: "\npost office, Gift o shop no 1 anupam society opp archana high school, cross road, near Naranpura, Naranpura, Ahmedabad, Gujarat 380013",
  phone: "\n098255 55821",
  email: "",
  website: "",
  mapUrl: "https://www.google.com/maps/place/Gift+'O'+Infinity/@23.0522664,72.5576386,17z/data=!3m1!4b1!4m6!3m5!1s0x395e8484e0bd44b1:0xf1391b894ddaa2ef!8m2!3d23.0522664!4d72.5576386!16s%2Fg%2F11bymwnnr4?entry=ttu&g_ep=EgoyMDI2MDUyNi4wIKXMDSoASAFQAw%3D%3D",
  latitude: "23.0522664",
  longitude: "72.5576386",
  rating: "",
  reviewsCount: "256",
  openingHours: "Show open hours for the week",
  logo: null,
  images: ["/images/gmap_1780051353564_0.jpg", "/images/gmap_1780051354138_1.jpg", "/images/gmap_1780051354689_2.jpg", "/images/gmap_1780051354970_3.jpg", "/images/gmap_1780051355140_4.jpg", "/images/gmap_1780051355490_5.jpg", "/images/gmap_1780051356104_6.jpg", "/images/gmap_1780051356562_7.jpg", "/images/gmap_1780051356962_8.jpg", "/images/gmap_1780051357098_9.jpg", "/images/gmap_1780051357260_10.jpg"],
  description: "",
  socials: {},
};

export const aiContent = {
  tagline: "Gifts from Heart of Ahmedabad",
  heroDescription: "Discover the perfect gift at Gift 'O' Infinity, located in the heart of Ahmedabad, near Naranpura. Our gift shop offers a wide range of unique and thoughtful presents. From elegant home decor to personalized items, we have something for everyone.",
  aboutTitle: "Our Gift Story",
  aboutText: "Located in the bustling streets of Ahmedabad, near the post office in Anupam Society, Gift 'O' Infinity is a treasure trove of gifts. Our shop is nestled in the vibrant Naranpura area, making it the perfect destination for those seeking special presents. With a passion for gift-giving, we curate our collection to ensure that every item is a reflection of love and care. Our team is dedicated to providing exceptional service, making every visit to our shop a memorable experience.",
  services: [
    { icon: "🎁", title: "Customized Gift Baskets", description: "Our expert team creates personalized gift baskets filled with a selection of items tailored to your needs, starting from ₹496" },
    { icon: "👫", title: "Gift Wrapping Services", description: "We offer beautifully crafted gift wrapping services, making your presents even more special, priced at ₹200 per item" },
    { icon: "📦", title: "Gift Delivery in Ahmedabad", description: "We provide convenient gift delivery services within Ahmedabad, starting from ₹300, ensuring your loved ones receive their gifts on time" },
    { icon: "🎉", title: "Birthday Gift Collection", description: "Our curated birthday gift collection features a range of exciting items, including cakes, balloons, and more, starting from ₹800" },
    { icon: "💕", title: "Anniversary Gift Selection", description: "We offer a thoughtful selection of anniversary gifts, including personalized items and romantic experiences, priced between ₹1200 and ₹2586" },
    { icon: "👶", title: "Baby Shower Gift Ideas", description: "Our baby shower gift collection features adorable and practical items for the new baby, starting from ₹600" }
  ],
  whyChooseUs: [
    { icon: "📍", title: "Convenient Location", description: "Gift 'O' Infinity is strategically located near Naranpura, making it easily accessible for residents and visitors alike" },
    { icon: "💯", title: "Unique Gift Collection", description: "Our gift shop features a diverse range of unique and thoughtful presents, ensuring you find the perfect gift for every occasion" },
    { icon: "🤝", title: "Personalized Service", description: "Our team is dedicated to providing exceptional service, making every visit to our shop a memorable experience" },
    { icon: "🎁", title: "Competitive Pricing", description: "We offer competitive pricing for our gifts and services, ensuring you get the best value for your money" }
  ],
  testimonials: [
    { name: "Hema Trivedi", role: "Frequent Customer", text: "I've been visiting Gift 'O' Infinity for years, and their customized gift baskets are always a hit with my loved ones. The team is friendly and helpful, making every visit a pleasure.", rating: 5 },
    { name: "Hiren Desai", role: "Corporate Client", text: "We've been using Gift 'O' Infinity's gift wrapping services for our corporate events, and the feedback has been outstanding. Their attention to detail and professionalism are truly impressive.", rating: 5 },
    { name: "Harshita Mehta", role: "New Customer", text: "I recently discovered Gift 'O' Infinity, and I'm so glad I did. Their anniversary gift selection is amazing, and the team helped me find the perfect present for my partner.", rating: 5 }
  ],
  faq: { items: [{ question: "What are your business hours?", answer: "Gift 'O' Infinity is open from 10 am to 8 pm, Monday to Sunday. Please note that our hours may vary on public holidays, so it's best to call us at 098255 55821 to confirm." },
    { question: "Do you offer gift delivery services?", answer: "Yes, we provide convenient gift delivery services within Ahmedabad, starting from ₹300. Please contact us for more information on delivery areas and pricing." },
    { question: "Can I customize my gift basket?", answer: "Absolutely! Our team would be happy to help you create a personalized gift basket filled with items tailored to your needs. Please visit us in-store or call us at 098255 55821 to discuss your requirements." },
    { question: "Do you have a loyalty program?", answer: "Yes, we have a loyalty program that rewards our frequent customers with exclusive discounts and offers. Please ask our team about the program details and how to join." },
    { question: "Can I return or exchange a gift?", answer: "Yes, we have a return and exchange policy in place. Please contact us within 7 days of purchase to initiate the process. Our team will be happy to assist you." },
    { question: "How do I track my order?", answer: "Once your order is shipped, you will receive a tracking number via email. You can use this number to track the status of your order on our website or by contacting our customer service team." }] },
  ctaTitle: "Find Your Perfect Gift Today",
  ctaDescription: "Visit us in-store or call us to discover the perfect gift for your loved ones. Our team is always happy to help.",
  ctaButtonText: "Explore Gifts",
  metaDescription: "Gift 'O' Infinity, Ahmedabad's premier gift shop, offers unique gifts and personalized services.",
};

export const siteConfig = {
  layout: "organic-shapes",
  theme: "elegant",
  sections: ["services", "contact", "gallery", "about", "faq", "testimonials"],
  heroVariant: "before-after-showcase",
  navStyle: "hamburger-menu",
  animationStyle: "parallax-sections",
  cardStyle: "rounded-3xl border-2 border-dashed",
  darkMode: false,
};
